### ISSUE TITLE
Edit to remove resolved tickets from the report

### ISSUE THREAD

**Issue by chandler05** [mojira/r-isa#19]
Potentially a whitelist of resolutions to keep as well

**Comment by urielsalis** [comment]
As we always generate a new report from 0, they get overriden anyway :D

**Comment by SPGoding** [comment]
When Galaxy is doing it, they keep certain resolved tickets (e.g. Fixed or WAI, iirc) with a ~~strikethrough~~. We might actually not want to generate report from 0.
