### ISSUE TITLE
Bot does not escape underscores and other characters in issue titles

### ISSUE THREAD

**Issue by Pokechu22** [mojira/r-isa#34]
## The Bug

The bot fails to escape markdown characters in issue titles.  For instance, `block.pointed_dripstone.drip_[liquid/cauldron] has no subtitles` renders as <q>block.pointed<i>dripstone.drip</i>[liquid/cauldron] has no subtitles</q>.  (This example only happens on old reddit; new reddit (and GitHub)'s markdown don't italicise it here.  But, other titles may run into the problem.)

## Example

https://www.reddit.com/r/Mojira/comments/k0vxpp/bugtracker_report_20w48a/

## Expected Behavior

Markdown characters should be escaped.  I don't have a complete list, but probably `_`, `*`, `(`, `)`, `[`, `]`, <code>\`</code>, and `\` should be escaped by putting a backslash before them.  At least in my quick tests (with old reddit; new reddit may be different), that prevents them from showing up and the backslash doesn't appear in the rendered output either (even if the formatting wouldn't have done anything in that situation).  For the example, this would be `block.pointed\_dripstone.drip\_\[liquid/cauldron\] has no subtitles`.

**Comment by SPGoding** [comment]
From the [Official Markdown Syntax](https://daringfireball.net/projects/markdown/syntax#backslash) (linked from [here](https://www.reddit.com/wiki/commenting#wiki_commenting)):

> Markdown provides backslash escapes for the following characters:
> 
> \\   backslash
> \`   backtick
> \*   asterisk
> \_   underscore
> \{}  curly braces
> \[]  square brackets
> \()  parentheses
> \#   hash mark
> \+   plus sign
> \-   minus sign (hyphen)
> \.   dot
> \!   exclamation mark

**Comment by Pokechu22** [comment]
What about `~` and `^`?  Those don't seem to have been in the original markdown specification, but work on reddit.

**Comment by SPGoding** [comment]
Thanks, updated the regex in #35 respectively.
